name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  sonar-check:
    name: SonarCloud Check
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH
        shell: pwsh

      - name: SonarScanner Begin
        run: |
          dotnet sonarscanner begin `
            /k:"<Project Key>" `
            /o:"<Organization Key>" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.cs.opencover.reportsPaths="**/coverage.xml" `
            /d:sonar.cpd.cs.minimumTokens=40 `
            /d:sonar.cpd.cs.minimumLines=5 `
            /d:sonar.exclusions=**/bin/**,**/obj/**,**/sonarcloud.yml `
            /d:sonar.qualitygate.wait=true
        shell: pwsh

      - name: Build
        run: dotnet build YourSolution.sln -c Release --no-restore

      - name: SonarScanner End
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        shell: pwsh
